# -*- coding: utf-8 -*-
"""ex2_loop

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19J21DpDqO02vdmkXfQEhjH3Nb9-1tYKx
"""

num = int(input("Enter a number: "))
if num < 0:
   print("Enter a positive number")
else:
   sum = 0
   # use while loop to iterate un till zero
   while(num > 0):
       sum += num
       num -= 1
   print("The sum is",sum)

a = int(input('Enter first number : '))
b = int(input('Enter second number : '))
c = int(input('Enter third number : '))
largest = 0
if a > b and a > c :
 largest = a
elif b > c :
 largest = b
else :
 largest = c
print(largest, "is the largest of three numbers.")

num=int(input("Enter a number:"))
temp=num
rev=0
while(num>0):
 dig=num%10
 rev=rev*10+dig
 num=num//10
if(temp==rev):
 print("The number is palindrome!")
else:
 print("Not a palindrome!")

num = float(input("Input a number: "))
if num > 0:
 print("It is positive number")
elif num == 0:
 print("It is Zero")
else:
 print("It is a negative number")

print("Prime Number checking using Python")
num = int(input("Enter the number"))
# If given number is greater than 1
if num > 1:
 # Iterate from 2 to n / 2
    for i in range(2, int(num/2)+1):
 # If num is divisible by any number between
 # 2 and n / 2, it is not prime
        if (num % i) == 0:
            print(num, "is not a prime number")
            break
    else:
       print(num, "is a prime number")
else:
  print(num, "is not a prime number")